# Generated by Django 5.1.7 on 2025-03-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('browsing_history', models.JSONField()),
                ('purchase_history', models.JSONField()),
                ('customer_segment', models.CharField(max_length=50)),
                ('avg_order_value', models.FloatField()),
                ('holiday', models.BooleanField()),
                ('season', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=100)),
                ('avg_rating_similar_products', models.FloatField()),
                ('product_rating', models.FloatField()),
                ('review_sentiment_score', models.FloatField()),
                ('holiday', models.BooleanField()),
                ('season', models.CharField(max_length=20)),
                ('geographical_location', models.CharField(max_length=100)),
                ('similar_product_list', models.JSONField()),
                ('probability_of_recommendation', models.FloatField()),
            ],
        ),
    ]
